FROM ubuntu:latest


# docker compose up --build

RUN apt-get update && apt-get install curl -y


# https://cli.devin.ai/install.sh


WORKDIR /data

# interaction required
# RUN curl -fsSL https://cli.devin.ai/install.sh | bash


RUN echo "hi"